name: "Jest Tests"

on:
  pull_request:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run test:ci
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: coverage/test-reports/jest-junit.xml

  test-report:
    name: Test Report
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-reports
      - name: Generate Test Report
        uses: dorny/test-reporter@v1.9.0
        if: success() || failure()
        with:
          name: JEST Tests
          path: test-reports/jest-junit.xml
          reporter: jest-junit
